const languageContent = {
  en: {
    title01: 'Target',
    firstName: 'Iryna',
    lastName: 'Lysenko',
    workAs: 'Economist',
    target:
      'To leverage my expertise in financial analysis, client service, and risk management in a forward-thinking organization, contributing to its growth while pursuing opportunities for professional development and leadership',
    title02: 'Contacts',
    address: 'Most, Czech Republic, 43401',
    phone: '+380 993 586 505 (messengers)',
    title03: 'Skills',
    title04: 'Social Media',
    title05: 'About',
    about:
      'I am an results-driven professional with a degree in Economics and over 2 years of experience in the banking sector. Skilled in financial analysis, client service, and risk management. Highly organized, adaptable, and committed to continuous professional growth. Seeking new opportunities to apply my expertise and contribute to a dynamic team',
    title06: 'Education',
    education01: 'Technological and Economic College - forwarder',
    education02: 'Kharkiv State University of Food and Trade - economist',
    // education03: 'Self-education on web technologies',
    title07: 'Experience',
    course01: 'Clothing store "Monton" - sales consultant',
    course02: 'PE "Svir-Medica" - manager',
    course03: 'Shop "Chobitok" - sales consultant',
    course04: 'Bank "A-Bank" - credit specialist',
    title08: 'Languages',
    lang01: 'ukrainian (native)',
    lang02: 'english - elementary (A2)',
    lang03: 'czech - elementary (A2)',
    // title09: 'Projects',
    // project01: '[The application helps to buy, sell or rent estate]',
    // project02:
    //   '[The application helps to select exercises to work out with any muscles with examples and video]',
    // project03:
    //   '[The app helps to manage books: CRUD, add books randomly with API, filter books, make them favorite]',
  },
  cz: {
    title01: 'Účel práce',
    firstName: 'Iryna',
    lastName: 'Lysenko',
    workAs: 'Ekonom',
    target:
      'Chci využít své zkušenosti v oblasti ekonomických analýz, služeb zákazníkům a řízení rizik v organizaci zaměřené na budoucnost, přispět k jejímu růstu a zároveň hledat příležitosti pro profesní rozvoj a vedení.',
    title02: 'Kontakty',
    address: 'Most, Česká republika, 43401',
    phone: '+3380 993 586 505 (posly)',
    title03: 'Dovednosti',
    title04: 'Sociální média',
    title05: 'O sobě',
    about:
      'Jsem profesionál orientovaný na výsledky s ekonomickým vzděláním a více než 2 roky zkušeností v bankovním sektoru. Má dovednosti v oblasti ekonomické analýzy, zákaznického servisu a řízení rizik. Vysoce organizovaný, přizpůsobivý a oddaný neustálému profesnímu růstu. Hledám nové příležitosti, jak uplatnit své zkušenosti a přispět do dynamického týmu.',
    title06: 'Vzdělání',
    education01: 'Vysoká škola technická a ekonomická - komoditní expert',
    education02: 'Kharkiv státní univerzita jídla a obchodu - ekonom',
    // education03: 'Sebevzdělávání na webových technologiích',
    title07: 'Zažít',
    course01: 'Prodejna oděvů "Monton" - prodejní poradce',
    course02: 'Soukromý podnik "Svir-Medica" - manažer',
    course03: 'Prodejna Chobitok - prodejní poradce',
    course04: 'Banka "A-Bank" - úvěrový specialista',
    title08: 'Jazyky',
    lang01: 'ukrajinský (rodilý)',
    lang02: 'angličtina - začátečník (A2)',
    lang03: 'čeština - začátečník (A2)',
    // title09: 'Projekty',
    // project01: '[Aplikace pomáhá koupit, prodat nebo pronajmout nemovitost]',
    // project02:
    //   '[Aplikace pomáhá vybrat cvičení pro cvičení s jakýmikoli svaly příklady a videa]',
    // project03:
    //   '[Aplikace pomáhá spravovat knihy: přidat knihy ručně, náhodně z místního souboru.JSON a náhodně pomocí rozhraní API učinit knihy oblíbenými filtrovat je podle názvu, autora a oblíbených položek, vymazat]',
  },
  ua: {
    title01: 'Мета',
    firstName: 'Ірина',
    lastName: 'Лисенко',
    workAs: 'Eкономіст',
    target:
      'Я прагну використовувати свій досвід у економічному аналізі, обслуговуванні клієнтів і управлінні ризиками в перспективній організації, сприяючи її зростанню, одночасно шукаючи можливості для професійного розвитку та лідерства',
    title02: 'Контакти',
    address: 'м. Мост, Чехія, 43401',
    phone: '+380 993 586 505 (мессенджери)',
    title03: 'Навички',
    title04: 'Соціальні мережі',
    title05: 'Про себе',
    about:
      'Я професіонал, орієнтований на результат, маю економічну освіту та досвід роботи в банківському секторі понад 2 роки. Має навички економічного аналізу, обслуговування клієнтів та управління ризиками. Високо організований, адаптивний і прагне постійного професійного зростання. Шукаю нові можливості застосувати свій досвід і зробити внесок у динамічну команду',
    title06: 'Освіта',
    education01: 'Технологічно-економічний коледж  - товарознавець',
    education02:
      'Харківський державний університет харчування та торгівлі - економіст',
    // education03: 'самонавчання веб-девелопер',
    title07: 'Досвід',
    course01: 'Магазин одягу «Monton» - продавець консультант',
    course02: 'ПП «Свір-Медіка» - менеджер',
    course03: 'Магазин взуття «Чобіток» - продавець-консультант',
    course04: 'Банк «А-Банк» - кредитний спеціаліст',
    title08: 'Мови',
    lang01: 'українська (рідна)',
    lang02: 'англійська - початківець (А2)',
    lang03: 'чеська - початківець (A2)',
    // title09: 'Проєкти',
    // project01: '[Допомагає купити, продати, орендувати нерухомість]',
    // project02:
    //   '[Допомагає обрати вправи для роботи з будь-якими м`язами з відео-прикладами]',
    // project03:
    //   '[Допомагає керувати переліком книг (CRUD): додавати книги вручну, обирати випадкові книги з локального файлу JSON і випадково за допомогою API, позначати обрані книги, фільтрувати їх за назвою, автором і з обраних]',
  },
};

export default languageContent;
